OpenMAMA C++ API: Wombat::MamaFieldCacheField Class Reference
Wombat::MamaFieldCacheField Class Reference
The MamaFieldCacheField class is used to store the information on the type of a field and its value(s).
#include <MamaFieldCacheField.h>
Public Member Functions
MamaFieldCacheField ()
Constructor.
virtual ~MamaFieldCacheField ()
Destructor.
MamaFieldCacheField (const MamaFieldCacheField &rhs)
Copy constructor.
MamaFieldCacheField & operator= (const MamaFieldCacheField &rhs)
Copy rhs into the current object.
bool operator== (const MamaFieldCacheField &rhs) const
Return if the current field is equal to the specified field.
bool operator!= (const MamaFieldCacheField &rhs) const
Return if the current field is different from the specified field.
virtual void create (const MamaFieldDescriptor &descriptor)
Create a MamaFieldCacheField.
virtual void create (mama_fid_t fid, mamaFieldType type, const char *name=NULL)
Create a MamaFieldCacheField.
virtual void clear ()
Clear the MamaFieldCacheField.
virtual mama_fid_t getFid () const
Return the field id.
virtual mamaFieldType getType () const
Return the field type.
const char * getName () const
Return the name of the field.
void setDescriptor (const MamaFieldDescriptor *descriptor)
Set the descriptor of the field.
const MamaFieldDescriptor * getDescriptor () const
Return the descriptor of the field.
virtual bool isModified () const
Return whether the field has been modified or not.
virtual void setPublish (bool value=true)
Set the publish flag of the field.
virtual bool getPublish () const
Return the always publish flag of the field.
virtual void setCheckModified (bool value=true)
Set the checkModifed flag of a field.
virtual bool getCheckModified () const
Return the checkModified flag of the field.
virtual bool isVector () const
Return if the field is a vector (otherwise is a single-value field).
mamaFieldCacheField & getCValue ()
const mamaFieldCacheField & getCValue () const
Detailed Description
The MamaFieldCacheField class is used to store the information on the type of a field and its value(s).
This class does not provide methods to set and get the value (check the specific types of fields such as MamaFieldCacheFieldBool).
Constructor & Destructor Documentation
Wombat::MamaFieldCacheField::MamaFieldCacheField ()
Constructor.
Use create to create the actual field.
virtual Wombat::MamaFieldCacheField::~MamaFieldCacheField () [virtual]
Destructor.
This is called automatically when an object is destroyed. This method will clean all the memory allocated.
Wombat::MamaFieldCacheField::MamaFieldCacheField (const MamaFieldCacheField & rhs)
Copy constructor.
Parameters:
Member Function Documentation
MamaFieldCacheField& Wombat::MamaFieldCacheField::operator= (const MamaFieldCacheField & rhs)
Copy rhs into the current object.
Parameters:
rhs The source MamaFielCacheField.
Returns:
The MamaFieldCacheField itself.
bool Wombat::MamaFieldCacheField::operator== (const MamaFieldCacheField & rhs) const
Return if the current field is equal to the specified field.
Parameters:
rhs The other field to check equality.
Returns:
Whether the two fields are equal.
bool Wombat::MamaFieldCacheField::operator!= (const MamaFieldCacheField & rhs) const
Return if the current field is different from the specified field.
Parameters:
rhs The other field to check difference.
Returns:
Whether the two fields are different.
virtual void Wombat::MamaFieldCacheField::create (const MamaFieldDescriptor & descriptor) [virtual]
Create a MamaFieldCacheField.
Parameters:
descriptor Descriptor of the field to create.
virtual void Wombat::MamaFieldCacheField::create (mama_fid_t fid, mamaFieldType type, const char * name = NULL) [virtual]
Create a MamaFieldCacheField.
Parameters:
fid Field id of the field to create.
type Field type of the field to create.
name Name of the field to create.
virtual void Wombat::MamaFieldCacheField::clear () [virtual]
Clear the MamaFieldCacheField.
The field is ready to be used, as long as create has been called once.
virtual mama_fid_t Wombat::MamaFieldCacheField::getFid () const [virtual]
Return the field id.
If the field is not valid, then 0 is returned.
Returns:
The field id of the field.
virtual mamaFieldType Wombat::MamaFieldCacheField::getType () const [virtual]
Return the field type.
If the field is not valid, then MAMA_FIELD_TYPE_UNKNOWN is returned.
Returns:
The field type of the field.
Referenced by Wombat::MamaFieldCacheFieldDateTimeVector::checkType(), Wombat::MamaFieldCacheFieldPriceVector::checkType(), Wombat::MamaFieldCacheFieldStringVector::checkType(), Wombat::MamaFieldCacheFieldVectorBasic< T, fieldType >::checkType(), Wombat::MamaFieldCacheFieldDateTime::checkType(), Wombat::MamaFieldCacheFieldPrice::checkType(), Wombat::MamaFieldCacheFieldString::checkType(), Wombat::MamaFieldCacheFieldBasic< T, fieldType >::checkType(), Wombat::getFieldValue(), and Wombat::setFieldValue().
const char* Wombat::MamaFieldCacheField::getName () const
Return the name of the field.
If the name is not set, then NULL is returned.
Returns:
void Wombat::MamaFieldCacheField::setDescriptor (const MamaFieldDescriptor * descriptor)
Set the descriptor of the field.
Parameters:
descriptor Pointer to the descriptor of the field.
const MamaFieldDescriptor* Wombat::MamaFieldCacheField::getDescriptor () const
Return the descriptor of the field.
If the descriptor is not set, NULL is returned.
Returns:
Pointer to the descriptor of the field.
virtual bool Wombat::MamaFieldCacheField::isModified () const [virtual]
Return whether the field has been modified or not.
Returns:
Whether the field is modified.
virtual void Wombat::MamaFieldCacheField::setPublish (bool value = true) [virtual]
Set the publish flag of the field.
If set to false, the field is never published.
Parameters:
value The publish flag.
virtual bool Wombat::MamaFieldCacheField::getPublish () const [virtual]
Return the always publish flag of the field.
Returns:
The publish flag.
virtual void Wombat::MamaFieldCacheField::setCheckModified (bool value = true) [virtual]
Set the checkModifed flag of a field.
If set to true, the field will be checked for modification before publishing.
Parameters:
value The checkModified flag.
virtual bool Wombat::MamaFieldCacheField::getCheckModified () const [virtual]
Return the checkModified flag of the field.
Returns:
The check modified flag.
virtual bool Wombat::MamaFieldCacheField::isVector () const [virtual]
Return if the field is a vector (otherwise is a single-value field).
Returns:
If the field is a vector field.
mamaFieldCacheField& Wombat::MamaFieldCacheField::getCValue ()
const mamaFieldCacheField& Wombat::MamaFieldCacheField::getCValue () const